
CREATE TABLE escolas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cnpj TEXT UNIQUE,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE usuarios (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  email TEXT,
  role TEXT CHECK (role IN ('PROFESSOR', 'ALUNO', 'STAFF')) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE funcionarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  usuario_id UUID UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  cpf TEXT UNIQUE,
  rg TEXT UNIQUE,
  telefone TEXT,
  endereco TEXT,
  data_contratacao DATE,
  tipo_funcionario TEXT CHECK (tipo_funcionario IN ('PROFESSOR', 'STAFF'))
);

CREATE TABLE professores (
  id BIGINT PRIMARY KEY REFERENCES funcionarios(id) ON DELETE CASCADE,
  especialidade TEXT,
  formacao TEXT
);

CREATE TABLE secretaria_staff (
  id BIGINT PRIMARY KEY REFERENCES funcionarios(id) ON DELETE CASCADE,
  setor TEXT,
  cargo TEXT
);

-- 3. ALUNOS E FAMÍLIA
CREATE TABLE turmas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  ano_letivo INTEGER NOT NULL
);

CREATE TABLE alunos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  usuario_id UUID UNIQUE REFERENCES usuarios(id) ON DELETE SET NULL,
  nome TEXT NOT NULL,
  matricula TEXT,
  data_nasc DATE,
  data_matricula DATE DEFAULT CURRENT_DATE,
  rg TEXT,
  cpf TEXT,
  endereco TEXT,
  necessidades_especiais TEXT,
  turma_atual_id BIGINT REFERENCES turmas(id)
);

ALTER TABLE alunos ADD CONSTRAINT unique_matricula_escola UNIQUE (escola_id, matricula);

CREATE TABLE fichas_saude (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT UNIQUE REFERENCES alunos(id) ON DELETE CASCADE,
  alergias TEXT,
  medicamentos TEXT,
  contato_emergencia TEXT
);

CREATE TABLE responsaveis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  cpf TEXT,
  telefone TEXT
);

CREATE TABLE aluno_responsavel (
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  responsavel_id BIGINT REFERENCES responsaveis(id) ON DELETE CASCADE,
  parentesco TEXT,
  pode_retirar BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (aluno_id, responsavel_id)
);

-- 4. ESTRUTURA ACADÊMICA
CREATE TABLE periodos_letivos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  ano INTEGER NOT NULL,
  nome TEXT NOT NULL,
  data_inicio DATE,
  data_fim DATE,
  is_fechado BOOLEAN DEFAULT FALSE
);

CREATE TABLE disciplinas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  nome TEXT NOT NULL
);

CREATE TABLE matriculas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escola_id BIGINT REFERENCES escolas(id) ON DELETE CASCADE,
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  turma_id BIGINT REFERENCES turmas(id) ON DELETE CASCADE,
  ano INTEGER NOT NULL
);

-- 5. DIÁRIO DE CLASSE
CREATE TABLE aulas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turma_id BIGINT REFERENCES turmas(id) ON DELETE CASCADE,
  disciplina_id BIGINT REFERENCES disciplinas(id) ON DELETE CASCADE,
  professor_id BIGINT REFERENCES professores(id) ON DELETE SET NULL,
  periodo_id BIGINT REFERENCES periodos_letivos(id) ON DELETE SET NULL,
  data TIMESTAMPTZ NOT NULL,
  conteudo_ministrado TEXT,
  quantidade_aulas INTEGER DEFAULT 1
);

CREATE TABLE presencas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aula_id BIGINT REFERENCES aulas(id) ON DELETE CASCADE,
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('PRESENTE', 'FALTA', 'FALTA_JUSTIFICADA'))
);

-- 6. ATIVIDADES, NOTAS E IA
CREATE TABLE atividades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turma_id BIGINT REFERENCES turmas(id) ON DELETE CASCADE,
  disciplina_id BIGINT REFERENCES disciplinas(id) ON DELETE CASCADE,
  periodo_id BIGINT REFERENCES periodos_letivos(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  descricao_ia TEXT,
  formato TEXT CHECK (formato IN ('ONLINE', 'PRESENCIAL')),
  peso DECIMAL(5,2) DEFAULT 1.0,
  data_agendada TIMESTAMPTZ
);

CREATE TABLE entregas_alunos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atividade_id BIGINT REFERENCES atividades(id) ON DELETE CASCADE,
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  texto_resposta TEXT,
  arquivo_url TEXT,
  data_envio TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE notas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  atividade_id BIGINT REFERENCES atividades(id) ON DELETE CASCADE,
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  entrega_id BIGINT REFERENCES entregas_alunos(id) ON DELETE SET NULL,
  valor DECIMAL(5,2),
  feedback_ia TEXT,
  UNIQUE(atividade_id, aluno_id)
);

CREATE TABLE boletins_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id BIGINT REFERENCES alunos(id) ON DELETE CASCADE,
  turma_id BIGINT REFERENCES turmas(id) ON DELETE CASCADE,
  disciplina_id BIGINT REFERENCES disciplinas(id) ON DELETE CASCADE,
  periodo_id BIGINT REFERENCES periodos_letivos(id) ON DELETE CASCADE,
  media_final DECIMAL(5,2),
  total_faltas INTEGER,
  parecer_final TEXT,
  UNIQUE(aluno_id, disciplina_id, periodo_id)
);